insert into LEAGUES values( 1, 'Hong Kong FootBall League', 1, 2014, 'Autumn', 9 );
insert into LEAGUES values( 2, 'Hong Kong FootBall League', 1, 2015, 'Autumn', 9 );
insert into LEAGUES values( 3, 'Hong Kong FootBall League', 1, 2016, 'Autumn', 9 );
insert into LEAGUES values( 4, 'England Super League', 5, 2014, 'Summer', 3 );
insert into LEAGUES values( 5, 'England Super League', 4, 2015, 'Summer', 3 );
insert into LEAGUES values( 6, 'England Super League', 5, 2016, 'Summer', 3 );
insert into LEAGUES values( 7, 'England Winter League', 4, 2014, 'Winter', 3 );
insert into LEAGUES values( 8, 'England Winter League', 5, 2015, 'Winter', 3 );
insert into LEAGUES values( 9, 'England Winter League', 4, 2016, 'Winter', 3 );
insert into LEAGUES values( 10, 'China People League', 3, 2014, 'Spring', 1 );
insert into LEAGUES values( 11, 'China People League', 2, 2015, 'Spring', 1 );
insert into LEAGUES values( 12, 'China People League', 1, 2016, 'Spring', 1 );
insert into LEAGUES values( 13, 'J-League', 7, 2014, 'Autumn', 2 );
insert into LEAGUES values( 14, 'J-League', 7, 2015, 'Autumn', 2 );
insert into LEAGUES values( 15, 'J-League', 8, 2016, 'Spring', 2 );
insert into LEAGUES values( 16, 'Germany First Class League', 11, 2015, 'Summer', 6 );
insert into LEAGUES values( 17, 'Spain A Class League', 10, 2015, 'Autumn', 5 );
insert into LEAGUES values( 18, 'Brazil Summer League', 9, 2015, 'Summer', 4 );
insert into LEAGUES values( 19, 'Italy League', 6, 2015, 'Spring', 8 );
insert into LEAGUES values( 20, 'USA National League', 12, 2015, 'Spring', 7 );