/*
	Student ID: 1155009121
	Name: Lo Chun Tung
*/
/* Query 1 */
Spool result1.lst
SELECT LID,LEAGUE_NAME,TEAM_NAME,SEASON,YEAR FROM LEAGUES L, TEAMS T WHERE CHAMPION_TID=TID AND YEAR>=2012 AND YEAR<=2013 ORDER BY LID ASC;
Spool off
/* Query 2 */
Spool result2.lst
SELECT R.RID,REGION_NAME,FOOTBALL_RANKING FROM REGIONS R, LEAGUES L WHERE L.SEASON='Autumn' AND L.RID=R.RID GROUP BY R.RID,REGION_NAME,FOOTBALL_RANKING HAVING COUNT(*)>1 ORDER BY R.RID ASC;
Spool off
/* Query 3 */
Spool result3.lst
SELECT LID,LEAGUE_NAME,YEAR FROM LEAGUES L, TEAMS T WHERE L.CHAMPION_TID=T.TID AND T.AVERAGE_AGE=(SELECT MIN(T2.AVERAGE_AGE) FROM TEAMS T2) ORDER BY L.LID ASC;
Spool off
/* Query 4 */
Spool result4.lst
SELECT TID,TEAM_NAME,COUNT(*) AS L_NUM FROM LEAGUES L, TEAMS T WHERE CHAMPION_TID=TID GROUP BY TID,TEAM_NAME,CHAMPION_TID HAVING COUNT(*)>=2 ORDER BY TID DESC;
Spool off
/* Query 5 */
Spool result5.lst
SELECT SP.SID,SPONSOR_NAME,COUNT(*) AS L_Count FROM SPONSORS SP, SUPPORT SU WHERE SP.SID=SU.SID GROUP BY SP.SID,SPONSOR_NAME ORDER BY SP.SID DESC;
Spool off
/* Query 6 */
Spool result6.lst
SELECT SP.SID,SPONSOR_NAME FROM SPONSORS SP WHERE NOT EXISTS(SELECT * FROM LEAGUES L, REGIONS R, SUPPORT SU WHERE L.LID=SU.LID AND L.RID=R.RID AND SU.SID=SP.SID AND R.REGION_NAME='England') AND 2<=(SELECT COUNT(*) FROM SUPPORT SU WHERE SU.SID=SP.SID) ORDER BY SP.SID DESC;
Spool off
/* Query 7 */
Spool result7.lst
SELECT SP.SID,SPONSOR_NAME FROM SPONSORS SP, SUPPORT SU WHERE SU.SID=SP.SID AND EXISTS(SELECT * FROM LEAGUES L, REGIONS R WHERE L.LID=SU.LID AND L.RID=R.RID AND R.FOOTBALL_RANKING<10) AND 2<(SELECT SUM(SU2.SPONSORSHIP) FROM SUPPORT SU2 WHERE SU2.SID=SP.SID) ORDER BY SP.SID DESC;
Spool off
/* Query 8 */
Spool result8.lst
SELECT RID,REGION_NAME FROM REGIONS R WHERE EXISTS(SELECT * FROM LEAGUES L, SUPPORT SU WHERE L.RID=R.RID AND SU.LID=L.LID AND SU.SID IN (SELECT SID FROM SUPPORT SU GROUP BY SID HAVING COUNT(*)=(SELECT MAX(sCount) FROM (SELECT COUNT(*) AS sCount FROM SUPPORT SU2 GROUP BY SU2.SID)))) ORDER BY RID ASC;
Spool off
